services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stackoverflow_lite
      - MYSQL_TCP_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stackoverflow-network
  keycloak:
    depends_on:
      - mysql
    image: quay.io/keycloak/keycloak:24.0.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_VENDOR=${DB_VENDOR}
      - DB_ADDR=${DB_ADDR}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=localhost
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    command: ["start-dev", "--http-port=${KEYCLOAK_PORT}", "--import-realm"]
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
    networks:
      - stackoverflow-network
  stackoverlow-lite-app:
    depends_on:
      - mysql
      - keycloak
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3307;Database=stackoverflow_lite;User=root;Password=root1234;
    volumes:
      - ./appsettings.Docker.json:/app/appsettings.json
    networks:
      - stackoverflow-network

volumes:
  mysql_persistent_data:
    
networks:
  stackoverflow-network:
    driver: bridge